[project]
name = "file-mover"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pillow>=12.0.0",
    "pyyaml>=6.0.3",
    "redis>=7.0.1",
]
